### ISSUE TITLE
Add prioritization order for phone 

### ISSUE THREAD

**Issue by rafalczwajda** [makissyan/makorakofon#3]
Please add argument for your project that allow to select which phone will be selected as first one. 
ex. AutoPhoneProperties Samsung 
will select from connected phones Samsung phone and choose it as a phone.1 device 
AutoPhoneProperties Nexus 
will select from connected phones Nexus phone and cooose it as phone.1
AutoPhoneProperties 
will choose as it is on list adb devices.

**Comment by makissyan** [comment]
Done
https://github.com/makissyan/makorakofon/commit/900311b296a7c3272156a4de13659761e396e78e
